org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.1
neo_version=21.1.219

mod_id=touhou_little_maid_maid_nouveau
mod_name=Touhou Little Maid: Maid Nouveau
mod_version=0.1.0
mod_group_id=com.touhoulittlemaid.maidnouveau
mod_authors=Maid Nouveau contributors

touhou_little_maid_file=7894267
ars_nouveau_version=5.10.6.1228
patchouli_version=1.21.1-93-NEOFORGE-SNAPSHOT
geckolib_version=4.7.6
curios_version=9.5.1
